"""Initial migration.

Revision ID: 09e8d43f7ef5
Revises: 
Create Date: 2022-06-28 22:58:22.560435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e8d43f7ef5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('thread_ts', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('ts')
    )
    op.create_table('threads_to_follow',
    sa.Column('thread_ts', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('thread_ts')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threads_to_follow')
    op.drop_table('message')
    # ### end Alembic commands ###
